# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4898b5ceb334f3f559a4dee27517fa6c6ea6b480aedd603bff886e1ecf269a9b2f96417038df6be67d0f3e3421ade0536f0e13c3538ac1d96db128bcc7e62659

test:
  secret_key_base: fd84c827fe2b5247d3ca56d3d3985c41f139fc4e9c93dd8773beb676fa13310048ab5c9992b65bcd7fd21eb199503eaf50023f42a9b2ff90b76db4c9882a89d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
